name: 'Build and test'
description: 'Common build and test action for my android projects'
runs:
  using: "composite"
  steps:
    - name: Build
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test