# Copyright © 2024 Brent Tunnicliff <brent@tunnicliff.dev>

name: 'Build and test'
description: 'Common build and test action for my android projects'
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: ./gradlew build
    - name: Run tests
      shell: bash
      run: ./gradlew test